// let b = 2

try {
   let a = 2 + b 

} catch (error) {
    console.log(error)
    // throw new Error("Ocorreu um erro no c√≥digo")
}

console.log("teste")